name: Build and Release
"on":
    push:
        branches:
            - main

jobs:
    release:
        name: Run Build and Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn
            - name: Install
              run: yarn install --ignore-engines --frozen-lockfile
            - name: Lint
              run: yarn lint
            - name: Clean
              run: yarn clean:packages
            - name: Build
              run: yarn build:packages
            - name: Release
              env:
                  GH_TOKEN: ${{ secrets.PAT }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn release
