name: Build and Release
"on":
    push:
        branches:
            - main

jobs:
    release:
        name: Run Build and Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: yarn
            - name: Lint
              run: yarn lint
            - name: Build
              run: yarn build
            - name: Typecheck
              run: yarn typecheck
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn semantic-release