name: CI

on:
    push:
        branches:
            - "*"

    pull_request:
        branches:
            - "*"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install yarn
              run: npm install -g yarn

            - name: Set node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: yarn

            - name: Setup
              run: yarn global add @antfu/ni

            - name: Install
              run: nci --ignore-engines

            - name: Lint
              run: nr lint

    test:
        runs-on: ${{ matrix.os }}
        needs: lint

        strategy:
            matrix:
                node: [14.x, 15.x, 16.x]
                os: [ubuntu-latest, windows-latest, macos-latest]
            fail-fast: true

        steps:
            - uses: actions/checkout@v3

            - name: Install yarn
              run: npm install -g yarn

            - name: Set node version to ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            - name: Setup
              run: yarn global add @antfu/ni

            - name: Install
              run: nci --ignore-engines

            - name: Build
              run: nr build

            - name: Typecheck
              run: nr typecheck
