name: CI

on:
    push:
        branches:
            - "*"

    pull_request:
        branches:
            - "*"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install yarn
              run: npm install -g yarn

            - name: Set node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: yarn

            - name: Install
              run: yarn install --ignore-engines

            - name: Lint
              run: yarn lint

    test:
        runs-on: ${{ matrix.os }}
        needs: lint

        strategy:
            matrix:
                node: [14.x, 15.x, 16.x]
                os: [ubuntu-latest, windows-latest, macos-latest]
            fail-fast: false

        steps:
            - uses: actions/checkout@v3

            - name: Install yarn
              run: npm install -g yarn

            - name: Set node version to ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            - name: Install
              run: yarn install --ignore-engines

            - name: Build
              run: yarn build

            - name: Typecheck
              run: yarn typecheck

    release:
        runs-on: ubuntu-latest
        needs: lint,test
        if: ${{ github.ref == 'refs/heads/main' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install yarn
              run: npm install -g yarn

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/
                  cache: yarn

            - run: yarn install --ignore-engines

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: yarn semantic-release
